# Generated by Django 4.1.5 on 2023-01-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='movil',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre completo del cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='entregado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
