# Generated by Django 4.1.5 on 2023-02-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clientes_movil_alter_articulos_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
    ]
